Traceback (most recent call last):
  File ".\main.py", line 47, in <module>
    loss = train_one_epoch(model, opt, ds, batch_size, scheduler, criterion)
  File ".\main.py", line 17, in train_one_epoch
    pred = model(noised, Ts)
  File "C:\Users\maxti\miniconda3\envs\pytorch\lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\maxti\miniconda3\envs\pytorch\lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\maxti\Documents\MiniProjects\DiffusionPerso\models\unet.py", line 152, in forward
    Ts_embed = torch.gather(self.pe, dim=0, index=Ts)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument index in method wrapper_CUDA_gather)